
#include <iostream>
#include "lib/lib.h"


int main()
{
	std::cout << "Hello World from C++!\n";

	GoString input;
	input.p = "Golang";

	//Calling c-shared function generated by cgo
	GoString res = getHelloWord(input); //DON"T KNOW HOW TO USE IT HERE
	
	std::string str;
	str.assign(res.p, res.n);

	//Printing the string returned by above function
	std::cout << str;
}
