
#include <iostream>
#include "lib/lib.h"


int main()
{
	std::cout << "Hello World from C++!\n";

	std::string golang = "Golang"; 
	GoString input; 
	input.p = golang.c_str(); 
	input.n = golang.size();

	//Calling c-shared function generated by cgo
	GoString res = getHelloWord(input);
	
	std::string str;
	str.assign(res.p, res.n);

	//Printing the string returned by above function
	std::cout << str;
}
