
#include <iostream>
#include "lib/lib.h"


int main()
{
	std::cout << "Hello World from C++!\n";

	//Calling c-shared function generated by cgo
	std::string str = getHelloWord("Golang");

	//Printing the string returned by above function
	std::cout << str;
}
